### ISSUE TITLE
Unneeded kernel version check

### ISSUE THREAD

**Issue by acmpo6ou** [dolikemedo/K6500ZE-Linux#1]
Hi @dolikemedo ! Thank you for this wonderful repo :)

I was helping my friend to fix the sound issues, and we didn't need to install a new kernel. Just running these magic commands helped:

```
sudo hda-verb /dev/snd/hwC0D0 0x20 0x500 0xf
sudo hda-verb /dev/snd/hwC0D0 0x20 0x400 0x7774
```
We also used your `setup.sh` to create a service that would execute the above commands on startup. However since we didn't do a kernel update your script just halted on this if check:
```bash
if uname -r | grep -q "5.15."; then
    show_help_kernel
    exit 1
fi
```
But as I mentioned we didn't need to do a kernel update, so this check was unnecessary for us. Do you think it should be removed?

**Comment by dolikemedo** [comment]
Thank you for the issue!
I fixed it. :-)
You have remained on 5.15 right?

**Comment by acmpo6ou** [comment]
I don't remember the version my friend had, honestly, sorry. Thanks for fixing this!
